name: test

on:
  pull_request:
    paths:
      - '.github/workflows/test.yaml'
      - 'actions/**/*.ts'
      - 'packages/**/*.ts'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test.yaml'
      - 'actions/**/*.ts'
      - 'packages/**/*.ts'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Set up Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
