name: test

on:
  pull_request:
    paths:
      - '.github/workflows/test.yaml'
      - 'actions/**/*.ts'
      - 'packages/**/*.ts'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test.yaml'
      - 'actions/**/*.ts'
      - 'packages/**/*.ts'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Node.js
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
