name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-node@v4.0.3
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: |
          npm run build
          npm run test
